### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by hemna** [aks/bash-lib#10]
I cloned the repo, then tried to run make as described in the install instructions.

  ass-vm  vagrant   master  ~  bash-lib  make
generate-prompt-colors
make: /usr/local/bin/bash: Command not found
Makefile:38: recipe for target 'prompt-colors.sh' failed
make: *** [prompt-colors.sh] Error 127

**Comment by aks** [comment]
Thanks for the report!  I'll fix it shortly.

**Comment by aks** [comment]
Fixed with rico-chet's PR.
